import { UHSFormData } from "@/types/uhsForm";

//the intialization for all the data
export const INITIAL_UHS_DATA: UHSFormData = {
  email: '',
  firstAgreement: false,
  secondAgreement: false,
  groupCategory: '',
  groupName: '',
  eventName: '',
  eventDesc: '',
  organizerName: '',
  organizerNumber: '',
  organizerEmail: '',
  location: '',
  numberOfParticipants: '',
  emergencyName: '',
  startDate: '',
  startTime: '',
  endDate: '',
  endTime: '',
  repeat: undefined,
  repeatInfo: '',
  execMeeting: undefined,
  thirdAgreement: false,
  virtual: undefined,
  movie: undefined,
  danger: undefined,
  activityDesc: '',
  nameOfFirstAidIndividual: '',
  nameOfEmergencyIndividual: '',
  fourthAgreement: false,
  fifthAgreement: false,
  involveHazard: undefined,
  equipmentDesc: '',
  certificateSent: false,
  sixthAgreement: false,
  food: undefined,
  alcohol: undefined,
  place: undefined,
  seventhAgreement: false,
  campus: undefined,
  eighthAgreement: undefined,
  travel: undefined,
  busName: '',
  busMonitor: '',
  safetyPlan: '',
  ninthAgreement: false,
  tenthAgreement: false,
  informationSecurityPolicy: false,
  studentRightsPolicy: false,
  discriminationHarassmentPolicy: false,
  sexualViolencePolicy: false,
  comments: '',
  finalAgreement: false,
};