import CouncilDetails from '@/types/CouncilDetails';

const deptAndProgramReps: CouncilDetails[] = [
  {
    firstName: 'Frank',
    lastName: 'Serafino',
    position: 'Chemical Engineering Rep',
    program: 'Chemical and Biomedical Engineering',
    level: 5,
    email: 'chemical@macengsociety.ca',
    image: '/images/council-24-25/frank-serafino.jpg',
    description: '',
  },
  {
    firstName: 'Saim',
    lastName: 'Umar',
    position: 'Civil Engineering Rep',
    program: 'Civil Engineering',
    level: 3,
    email: 'civil@macengsociety.ca',
    image: '/images/default-picture.jpeg',
    description: '',
  },
  {
    firstName: 'Majed',
    lastName: 'Kalaoun',
    position: 'Electrical & Computer Engineering Rep',
    program: 'Electrical Engineering',
    level: 3,
    email: 'ece@macengsociety.ca',
    image: '/images/council-24-25/majed-kalaoun.jpg',
    description: '',
  },
  {
    firstName: 'Bianka',
    lastName: 'Cestar',
    position: 'Engineering Physics Rep',
    program: 'Engineering Physics',
    level: 3,
    email: 'engphys@macengsociety.ca',
    image: '/images/council-24-25/bianka-cestar.jpg',
    description: '',
  },
  {
    firstName: 'Anna',
    lastName: 'Kocinski',
    position: 'Materials Engineering Rep',
    program: 'Materials Engineering',
    level: 3,
    email: 'materials@macengsociety.ca',
    image: '/images/default-picture.jpeg',
    description: '',
  },
  {
    firstName: 'Tyler',
    lastName: 'Fessenden',
    position: 'Mechanical Engineering Rep',
    program: 'Mechanical Engineering and Society',
    level: 4,
    email: 'mechanical@macengsociety.ca',
    image: '/images/council-24-25/tyler-fessenden.jpg',
    description: '',
  },
  {
    firstName: 'Marko',
    lastName: 'Buha',
    position: 'Mechatronics Engineering Rep',
    program: 'Mechatronics Engineering',
    level: 4,
    email: 'mechatronics@macengsociety.ca',
    image: '/images/default-picture.jpeg',
    description: '',
  },
  {
    firstName: 'Michael',
    lastName: 'Roberts',
    position: 'Software Engineering Rep',
    program: 'Software Engineering',
    level: 3,
    email: 'software@macengsociety.ca',
    image: '/images/council-24-25/michael-roberts.jpg',
    description: '',
  },
  {
    firstName: 'Faith',
    lastName: 'Law',
    position: 'Bachelor of Technology (B.Tech) Rep',
    program: 'Biotechnology',
    level: 1,
    email: 'btech@macengsociety.ca',
    image: '/images/council-24-25/faith-law.jpeg',
    description: '',
  },
  {
    firstName: 'Grady',
    lastName: 'Rueffer',
    position: 'Computer Science Rep',
    program: 'Computer Science',
    level: 1,
    email: 'compsci@macengsociety.ca',
    image: '/images/council-24-25/grady-rueffer.png',
    description: '',
  },
  {
    firstName: 'Agnes',
    lastName: 'Kung',
    position: 'iBiomedical Engineering Rep',
    program: 'iBiomedical Engineering',
    level: 1,
    email: 'ibiomed@macengsociety.ca',
    image: '/images/council-24-25/agnes-kung.jpg',
    description: '',
  },
  {
    firstName: 'Nesa',
    lastName: 'Gonsalves',
    position: 'Engineering & Management Rep',
    program: 'Civil Engineering and Management',
    level: 3,
    email: 'management@macengsociety.ca',
    image: '/images/council-24-25/nesa-gonsalves.jpg',
    description: '',
  },
  {
    firstName: 'Bilal',
    lastName: 'Karjikar',
    position: 'Engineering & Society Rep',
    program: 'Civil Engineering & Society',
    level: 3,
    email: 'society@macengsociety.ca',
    image: '/images/council-24-25/bilal-karjikar.jpg',
    description: '',
  },
];

export default deptAndProgramReps;
