import CouncilDetails from '@/types/CouncilDetails';

const deptAndProgramReps: CouncilDetails[] = [
  {
    firstName: 'Frank',
    lastName: 'Serafino',
    position: 'Chemical Engineering Rep',
    program: 'Chemical and Biomedical Engineering',
    level: 5,
    email: 'chemical@macengsociety.ca',
    image: '/images/council-24-25/frank-serafino.jpg',
    description:
      'Hello all! I will be the Chem Eng rep for the upcoming year! Please don’t hesitate to contact me if you have any questions or concerns about the faculty or the MES. I will always advocate for Chem Eng and spread the word on all things chem to help grow our faculty!',
  },
  {
    firstName: 'Saim',
    lastName: 'Umar',
    position: 'Civil Engineering Rep',
    program: 'Civil Engineering',
    level: 3,
    email: 'civil@macengsociety.ca',
    image: '/images/default-picture.jpeg',
    description:
      "Hi, I’m Saim, your Civil Engineering rep for this year. Civil is super interesting and I love taking part in technical teams and getting to connect with fellow students. As the rep for the world's second oldest profession, I want to help students feel more comfortable and reduce any unnecessary stress. Feel free to reach out by email or talk to me with any concerns you may have so I can try to help.",
  },
  {
    firstName: 'Majed',
    lastName: 'Kalaoun',
    position: 'Electrical & Computer Engineering Rep',
    program: 'Electrical Engineering',
    level: 3,
    email: 'ece@macengsociety.ca',
    image: '/images/council-24-25/majed-kalaoun.jpg',
    description:
      "Hello, I'm Majed, your current ECE rep. My role is to communicate between the ECE department and the MES. Feel free to reach out to me in-person or via email to chat about any concerns or ideas you want raised, as well as any questions you may have.",
  },
  {
    firstName: 'Bianka',
    lastName: 'Cestar',
    position: 'Engineering Physics Rep',
    program: 'Engineering Physics',
    level: 3,
    email: 'engphys@macengsociety.ca',
    image: '/images/council-24-25/bianka-cestar.jpg',
    description:
      "Hello everyone, my name is Bianka and I'm this year's engineering physics rep. Alongside being the EngPhys rep at MES, I am also a president at engineering physics society, so if you ever have any questions about the program please feel free to reach out to me! As an EngPhys rep, I'm really excited to be here and assist the Engineering Physics community however I can to provide everyone with the best possible experience in the program.",
  },
  {
    firstName: 'Anna',
    lastName: 'Kocinski',
    position: 'Materials Engineering Rep',
    program: 'Materials Engineering',
    level: 3,
    email: 'materials@macengsociety.ca',
    image: '/images/default-picture.jpeg',
    description:
      "Hi! My name is Anna and I am the Materials Department Rep this year. The purpose of my role is to communicate between the MES and the MSE. I also communicate your ideas to the respective societies, so if you have any ideas, questions, or concerns, please don't hesitate to reach out to me at any time! I'm excited to help make this school year amazing!!",
  },
  {
    firstName: 'Tyler',
    lastName: 'Fessenden',
    position: 'Mechanical Engineering Rep',
    program: 'Mechanical Engineering and Society',
    level: 4,
    email: 'mechanical@macengsociety.ca',
    image: '/images/council-24-25/tyler-fessenden.jpg',
    description: '',
  },
  {
    firstName: 'Marko',
    lastName: 'Buha',
    position: 'Mechatronics Engineering Rep',
    program: 'Mechatronics Engineering',
    level: 4,
    email: 'mechatronics@macengsociety.ca',
    image: '/images/default-picture.jpeg',
    description:
      "Hey, I'm Marko. I'm in my 4th and final year of the best engineering program at this school. As Tron Rep, I look forward to communicating our viewpoints to the McMaster Engineering Society and the Engineering Faculty. Feel free to contact me with any questions or concerns, and let's make this year the best one so far!",
  },
  {
    firstName: 'Michael',
    lastName: 'Roberts',
    position: 'Software Engineering Rep',
    program: 'Software Engineering',
    level: 3,
    email: 'software@macengsociety.ca',
    image: '/images/council-24-25/michael-roberts.jpg',
    description:
      "Hey everyone! I'm dedicated to advocating on your behalf to ensure you have the best year possible! I also contribute to the Software Engineering Society's events and website development. Outside of student government, I am an avid GTHA sports fan and a strategy board games enthusiast. Please don't hesitate to reach out to me, especially regarding a concern or suggestion about the MES or SES!",
  },
  {
    firstName: 'Faith',
    lastName: 'Law',
    position: 'Bachelor of Technology (B.Tech) Rep',
    program: 'Biotechnology',
    level: 1,
    email: 'btech@macengsociety.ca',
    image: '/images/council-24-25/faith-law.jpeg',
    description: '',
  },
  {
    firstName: 'Grady',
    lastName: 'Rueffer',
    position: 'Computer Science Rep',
    program: 'Computer Science',
    level: 1,
    email: 'compsci@macengsociety.ca',
    image: '/images/council-24-25/grady-rueffer.png',
    description: '',
  },
  {
    firstName: 'Agnes',
    lastName: 'Kung',
    position: 'iBiomedical Engineering Rep',
    program: 'iBiomedical Engineering',
    level: 1,
    email: 'ibiomed@macengsociety.ca',
    image: '/images/council-24-25/agnes-kung.jpg',
    description: '',
  },
  {
    firstName: 'Nesa',
    lastName: 'Gonsalves',
    position: 'Engineering & Management Rep',
    program: 'Civil Engineering and Management',
    level: 3,
    email: 'management@macengsociety.ca',
    image: '/images/council-24-25/nesa-gonsalves.jpg',
    description:
      'Hey everyone!! I’m Nesa, your Management Representative for 2024/2025. My role is to be a branch of communication between the MEMs, MES and student body. Feel free to reach out at any point with questions/concerns, ideas or even just to say hello :) Looking forward to an amazing year ahead!',
  },
  {
    firstName: 'Bilal',
    lastName: 'Karjikar',
    position: 'Engineering & Society Rep',
    program: 'Civil Engineering & Society',
    level: 3,
    email: 'society@macengsociety.ca',
    image: '/images/council-24-25/bilal-karjikar.jpg',
    description:
      "Hi! I'm Bilal, your Eng and Society rep for this year!! I am going into my third year of civil engineering and society program this fall, so hit that email button for any society questions you have. I want more people in Eng&Society, our classroom chairs are in need of awesome people like you!! ",
  },
  {
    firstName: 'Ifeyinwa',
    lastName: 'Mbielu',
    position: 'Engineering 1 MES Liaison',
    program: 'Engineering',
    level: 1,
    email: 'mbielui@mcmaster.ca',
    image: '/images/council-24-25/ifeyinwa-mbielu.jpeg',
    description: '',
  },
];

export default deptAndProgramReps;
