import CouncilDetails from '@/types/CouncilDetails';

const executives: CouncilDetails[] = [
  {
    firstName: 'Alexis',
    lastName: 'Moutafis-Tymcio',
    position: 'President',
    program: 'Software And Biomedical Engineering',
    level: 4,
    email: 'president@macengsociety.ca',
    image: '/images/council-24-25/alexis-moutafis-tymcio.jpg',
    description: '',
  },
  {
    firstName: 'Emily',
    lastName: 'Attai',
    position: 'Vice President, Academic',
    program: 'Materials And Biomedical Engineering',
    level: 3,
    email: 'vp.academic@macengsociety.ca',
    image: '/images/council-24-25/emily-attai.jpg',
    description: '',
  },
  {
    firstName: 'Annabelle',
    lastName: 'Heys',
    position: 'Vice President, Communications',
    program: 'Civil Engineering',
    level: 4,
    email: 'vp.communications@macengsociety.ca',
    image: '/images/council-24-25/annabelle-heys.jpg',
    description: '',
  },
  {
    firstName: 'Jackie',
    lastName: 'Fisher',
    position: 'Vice President, External',
    program: 'Materials Engineering and Society',
    level: 3,
    email: 'vp.external@macengsociety.ca',
    image: '/images/council-24-25/jackie-fisher.jpg',
    description: '',
  },
  {
    firstName: 'Luke',
    lastName: 'Schuurman',
    position: 'Vice President, Finance',
    program: 'Mechatronics Engineering',
    level: 6,
    email: 'vp.finance@macengsociety.ca',
    image: '/images/council-24-25/luke-schuurman.jpg',
    description: '',
  },
  {
    firstName: 'Muskaan',
    lastName: 'Opel',
    position: 'Vice President, Internal',
    program: 'Chemical Engineering and Bioengineering',
    level: 4,
    email: 'vp.internal@macengsociety.ca',
    image: '/images/council-24-25/muskaan-opel.jpg',
    description: '',
  },
  {
    firstName: 'Pedro',
    lastName: 'Cordeiro',
    position: 'Vice President, Student Life',
    program: 'Engineering Physics',
    level: 5,
    email: 'vp.studentlife@macengsociety.ca',
    image: '/images/council-24-25/pedro-cordeiro.jpg',
    description: '',
  },
];

export default executives;
