import CouncilDetails from '@/types/CouncilDetails';

const firstYearSocietyLeaders: CouncilDetails[] = [
  {
    firstName: 'Nicolas',
    lastName: 'Tran',
    position: 'Outreach Team Leader',
    program: 'iBiomedical Engineering',
    level: 1,
    email: 'trann42@mcmaster.ca',
    image: '/images/council-24-25/nicolas-tran.jpg',
    description: '',
  },
  {
    firstName: 'Mitchell',
    lastName: 'Fong',
    position: 'Events Team Leader',
    program: 'iBiomedical Engineering',
    level: 1,
    email: 'fongm21@mcmaster.ca',
    image: '/images/council-24-25/mitchell-fong.jpeg',
    description: '',
  },
  {
    firstName: 'Rian',
    lastName: 'Sen Majumder',
    position: 'First Year Council Chair',
    program: 'Engineering',
    level: 1,
    email: 'senmajur@mcmaster.ca',
    image: '/images/council-24-25/rian-senmajumder.jpg',
    description: '',
  },
  {
    firstName: 'Ifeyinwa',
    lastName: 'Mbielu',
    position: 'Engineering 1 MES Liaison',
    program: 'Engineering',
    level: 1,
    email: 'mbielui@mcmaster.ca',
    image: '/images/council-24-25/ifeyinwa-mbielu.jpeg',
    description: '',
  },
  {
    firstName: 'Faith',
    lastName: 'Law',
    position: 'First Year Bachelor of Technology (B.Tech) Rep',
    program: 'Biotechnology',
    level: 1,
    email: 'btech@macengsociety.ca',
    image: '/images/council-24-25/faith-law.jpeg',
    description: '',
  },
  {
    firstName: 'Grady',
    lastName: 'Rueffer',
    position: 'First Year Computer Science Rep',
    program: 'Computer Science',
    level: 1,
    email: 'compsci@macengsociety.ca',
    image: '/images/council-24-25/grady-rueffer.png',
    description: '',
  },
  {
    firstName: 'Agnes',
    lastName: 'Kung',
    position: 'First Year iBiomedical Engineering Rep',
    program: 'iBiomedical Engineering',
    level: 1,
    email: 'ibiomed@macengsociety.ca',
    image: '/images/council-24-25/agnes-kung.jpg',
    description: '',
  },
];

export default firstYearSocietyLeaders;
