export type Booking = {
  id: number;
  name: string;
  clubId: number;
  day: number;
  month: number;
  year: number;
  startTime: string;
  endTime: string;
  building: string;
  room: string;
  status: 'approved' | 'pending' | 'rejected';
};

export const sampleBookings = [
  {
    id: 1,
    name: 'Movie Night',
    clubId: 15,
    day: 30,
    month: 3,
    year: 2024,
    startTime: '12:00',
    endTime: '14:00',
    building: 'JHE',
    room: '311',
    status: 'approved' as Booking['status'],
  },
  {
    id: 2,
    name: 'Presentation',
    clubId: 1,
    day: 21,
    month: 1,
    year: 2024,
    startTime: '12:00',
    endTime: '14:00',
    building: 'MDCL',
    room: '112',
    status: 'rejected' as Booking['status'],
  },
  {
    id: 3,
    name: 'Social Event',
    clubId: 1,
    day: 7,
    month: 1,
    year: 2024,
    startTime: '12:00',
    endTime: '14:00',
    building: 'BSB',
    room: '107',
    status: 'pending' as Booking['status'],
  },
  {
    id: 4,
    name: 'Workshop',
    clubId: 1,
    day: 30,
    month: 5,
    year: 2024,
    startTime: '15:00',
    endTime: '17:00',
    building: 'PGCLL',
    room: '127',
    status: 'approved' as Booking['status'],
  },
  {
    id: 5,
    name: 'Presentation',
    clubId: 1,
    day: 30,
    month: 5,
    year: 2024,
    startTime: '15:00',
    endTime: '17:00',
    building: 'PGCLL',
    room: '127',
    status: 'approved' as Booking['status'],
  },
  {
    id: 6,
    name: 'Movie Night',
    clubId: 15,
    day: 30,
    month: 5,
    year: 2024,
    startTime: '12:00',
    endTime: '14:00',
    building: 'JHE',
    room: '311',
    status: 'approved' as Booking['status'],
  },
  {
    id: 7,
    name: 'Presentation',
    clubId: 1,
    day: 21,
    month: 5,
    year: 2024,
    startTime: '12:00',
    endTime: '14:00',
    building: 'MDCL',
    room: '112',
    status: 'rejected' as Booking['status'],
  },
  {
    id: 8,
    name: 'Social Event',
    clubId: 1,
    day: 7,
    month: 5,
    year: 2024,
    startTime: '12:00',
    endTime: '14:00',
    building: 'BSB',
    room: '107',
    status: 'pending' as Booking['status'],
  },
  {
    id: 9,
    name: 'Workshop',
    clubId: 1,
    day: 30,
    month: 5,
    year: 2024,
    startTime: '15:00',
    endTime: '17:00',
    building: 'PGCLL',
    room: '127',
    status: 'approved' as Booking['status'],
  },
  {
    id: 10,
    name: 'Presentation',
    clubId: 1,
    day: 7,
    month: 1,
    year: 2025,
    startTime: '15:00',
    endTime: '17:00',
    building: 'PGCLL',
    room: '127',
    status: 'approved' as Booking['status'],
  },
];

export const sampleBookings1 = [
  {
    id: 1,
    name: 'Movie Night',
    clubId: 15,
    day: 30,
    month: 3,
    year: 2024,
    startTime: '12:00',
    endTime: '14:00',
    building: 'JHE',
    room: '311',
    status: 'pending' as Booking['status'],
  },
  {
    id: 2,
    name: 'Presentation',
    clubId: 1,
    day: 21,
    month: 1,
    year: 2024,
    startTime: '12:00',
    endTime: '14:00',
    building: 'MDCL',
    room: '112',
    status: 'pending' as Booking['status'],
  },
  {
    id: 3,
    name: 'Social Event',
    clubId: 1,
    day: 7,
    month: 1,
    year: 2024,
    startTime: '12:00',
    endTime: '14:00',
    building: 'BSB',
    room: '107',
    status: 'pending' as Booking['status'],
  },
  {
    id: 4,
    name: 'Workshop',
    clubId: 1,
    day: 30,
    month: 5,
    year: 2024,
    startTime: '15:00',
    endTime: '17:00',
    building: 'PGCLL',
    room: '127',
    status: 'pending' as Booking['status'],
  },
  {
    id: 5,
    name: 'Presentation',
    clubId: 1,
    day: 30,
    month: 5,
    year: 2024,
    startTime: '15:00',
    endTime: '17:00',
    building: 'PGCLL',
    room: '127',
    status: 'pending' as Booking['status'],
  },
  {
    id: 6,
    name: 'Movie Night',
    clubId: 15,
    day: 30,
    month: 5,
    year: 2024,
    startTime: '12:00',
    endTime: '14:00',
    building: 'JHE',
    room: '311',
    status: 'pending' as Booking['status'],
  },
  {
    id: 7,
    name: 'Presentation',
    clubId: 1,
    day: 21,
    month: 5,
    year: 2024,
    startTime: '12:00',
    endTime: '14:00',
    building: 'MDCL',
    room: '112',
    status: 'pending' as Booking['status'],
  },
  {
    id: 8,
    name: 'Social Event',
    clubId: 1,
    day: 7,
    month: 5,
    year: 2024,
    startTime: '12:00',
    endTime: '14:00',
    building: 'BSB',
    room: '107',
    status: 'pending' as Booking['status'],
  },
  {
    id: 9,
    name: 'Workshop',
    clubId: 1,
    day: 30,
    month: 5,
    year: 2024,
    startTime: '15:00',
    endTime: '17:00',
    building: 'PGCLL',
    room: '127',
    status: 'pending' as Booking['status'],
  },
  {
    id: 10,
    name: 'Presentation',
    clubId: 1,
    day: 7,
    month: 1,
    year: 2025,
    startTime: '15:00',
    endTime: '17:00',
    building: 'PGCLL',
    room: '127',
    status: 'pending' as Booking['status'],
  },
];
